version: "3.5"

services:
  auth:
    image: quay.io/pusher/oauth2_proxy:v4.1.0
    container_name: radix-auth_container
    environment:
      - OAUTH2_PROXY_CLIENT_ID=23b07c34-ab93-4acf-968f-ba710a23f0b5
      - OAUTH2_PROXY_CLIENT_SECRET=<overide>
      - OAUTH2_PROXY_COOKIE_SECRET=<overide>
      - OAUTH2_PROXY_COOKIE_SECURE=false # only for development
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_HTTP_ADDRESS=http://:8000
      - OAUTH2_PROXY_OIDC_ISSUER_URL=https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/v2.0
      - OAUTH2_PROXY_PASS_ACCESS_TOKEN=true
      - OAUTH2_PROXY_PASS_BASIC_AUTH=false
      - OAUTH2_PROXY_PASS_USER_HEADERS=false
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost:8000/oauth2/callback
      - OAUTH2_PROXY_REDIS_CONNECTION_URL=redis://auth-state:6379
      - OAUTH2_PROXY_SCOPE=openid profile offline_access 23b07c34-ab93-4acf-968f-ba710a23f0b5/user_impersonation email # offline_access scope needed to get refresh token: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#successful-response-1
      - OAUTH2_PROXY_SESSION_STORE_TYPE=redis
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
      - OAUTH2_PROXY_UPSTREAMS=http://main:5000
    ports:
      - 8000:8000
    networks:
      - radix

  auth-state:
    image: redis:5-alpine
    container_name: radix-auth-state_container
    networks:
      - radix

  main:
    build: .
    container_name: main
    networks:
      - radix

networks:
  radix:
    name: radix
